### ISSUE TITLE
fork me, well fuck you!

### ISSUE THREAD

**Issue by 0xbrayo** [octocat/Spoon-Knife#19959]
inside joke

**Comment by macmaster** [comment]
watch your language. there might be kids on here.

**Comment by 0xbrayo** [comment]
I didn't think about that, sorry

**Comment by macmaster** [comment]
That's okay, I forgive you. The kids will turn out fine anyway... they always do.

**Comment by UbuntuLover1337** [comment]
i had the same thoughts and created PR #20332 to remedy the situation

**Comment by macmaster** [comment]
Thank you @UbuntuLover1337 , that was very productive.

**Comment by 0xbrayo** [comment]
wait... what?

**Comment by macmaster** [comment]
He made a PR to fix it. Click his PR in the comment.
