### ISSUE TITLE
gh pr checkout 24325

### ISSUE THREAD

**Issue by JefryMW23** [octocat/Spoon-Knife#26450]
gh pr checkout 24325

_Originally posted by @Chalo0 in https://github.com/octocat/Spoon-Knife/issues/24325#issuecomment-1059703295_

**Comment by Chalo0** [comment]
> gh pr checkout 24325
> 
> _Originally posted by @Chalo0 in [#24325 (comment)](https://github.com/octocat/Spoon-Knife/pull/24325#issuecomment-1059703295)_
