### ISSUE TITLE
eventmachine installation

### ISSUE THREAD

**Issue by eseosa** [octocat/Spoon-Knife#30]
Please how can I install eventmachine 0.12.10 on window. Whenever I try to install it, I usually get the message shown below:

$ gem install eventmachine
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

c:/Ruby192/bin/ruby.exe extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_thread_check_ints()... yes

**Comment by cameronmcefee** [comment]
Hi Eseosa,

This is a demo repo and is not used for support. Be sure to direct your eventmachine related questions to the [issues section of the eventmachine repo](https://github.com/eventmachine/eventmachine/issues)
