### ISSUE TITLE
Test the SK

### ISSUE THREAD

**Issue by kangmin** [octocat/Spoon-Knife#31]
is there a way to set a time for SK to STOP?

**Comment by cameronmcefee** [comment]
I'm not sure I understand the question. Can you elaborate?

**Comment by kangmin** [comment]
Hi,
i'm actually just experimenting with the issues for fork...

**Comment by cameronmcefee** [comment]
Ah, gotcha. Carry on and whatnot.

**Comment by chrisyco** [comment]
I think this relates to the issue of patching KDE on FreeBSD. If my memory doesn't fail, you can import patches into Git using `git import`. If you aren't using an SCM, you can apply patches easily using the `patch` command.
