### ISSUE TITLE
Issue list too disorganized

### ISSUE THREAD

**Issue by chrisyco** [octocat/Spoon-Knife#32]
The issues list is full of "testing 1-2-3" stuff and one-line pull requests which aren't actually bugs at all. Right now there are 1896 watchers, all of which will see anything you post here. Please do not waste any more of our precious time by adding more irrelevant comments.

**Comment by cameronmcefee** [comment]
Hi chrisyco,

I understand your concern with the notifications you receive. This repo, however, is for the purpose of learning and testing, so these people are using it to its intended purpose. If you would like to stop receiving notifications regarding this repo, you can click the "Unwatch" button at the top of the repo's home page. This is a test repo and will never be updated with anything pertinent. As such, there isn't really a need to continue watching it once the tutorials are completed. Feel free to do so without fear of missing anything important.
