### ISSUE TITLE
Triying to link a commit to this comment

### ISSUE THREAD

**Issue by cumanacr** [octocat/Spoon-Knife#4998]
Forgot description editing

**Comment by cumanacr** [comment]
Ok partially works!? the commit links to whole issue, not on a specific comment, back to the drawing board

**Comment by cumanacr** [comment]
Still not luck, trying now with Markdown

**Comment by cumanacr** [comment]
Markdown not works on commits I give up, with `#` works at least

**Comment by zhuruvl** [comment]
Another comment
